---
- name: congigure httpd
  hosts: all
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest
    - name: start service
      service:
        name: httpd
        state: restarted
        enabled: yes
