---
- name: Using jinja templates
  hosts: all
  tasks:
    - name: create template
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: "0644"
 
