---
- name: configure mariadb server
  hosts: all
  vars:
    db_package: mariadb-server
    db_service: mariadb
    db_users:
      - db_admin
      - db_lijo
    configure_db_path: /etc/my.cnf
  tasks:
  - name: create users
    user: 
      name: "{{ item }}"
    with_items: "{{ db_users }}"
  - name: install mariadb server
    yum: 
      name: "{{ db_package }}"
    when: db_package is defined
  - name: config
    include: config.yaml
    vars: 
      extra_packages:
        - mariadb-bench
        - mariadb-libs
        - mariadb-test
    when: config_db_path is defined
  - name: start service
    service: 
      name: "{{ db_service }}"
      state: restarted
      enabled: true
